#### multipal linear regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('housing.csv')

In [22]:
df = df.dropna()

In [42]:
df.head()

Age  Sex  Chest Pain  Shortest of breath  Heaviness or tightness  \
0   31    1           1                   1                       0   
1   24    0           1                   1                       0   
2   50    0           1                   1                       0   
3   36    0           1                   1                       0   
4   40    1           0                   1                       0   

   Radiation into arms nack and jaw  Congestion or burning  \
0                                 0                      1   
1                                 0                      1   
2                                 0                      0   
3                                 0                      0   
4                                 0                      0   

   Abnormal breathing  Losing flat cause  Decrease of sterngth  ...  Fever  \
0                   0                  0                     0  ...      0   
1                   1                  0                     0  ...      0   
2                   0                  0                     1  ...      0   
3                   1                  0                     0  ...      0   
4                   1                  0                     0  ...      0   

   Clubbing  Rash  Smocking  Hypertension  Hyperchoies terolamia  Myocandial  \
0         0     0         0             0                      0           0   
1         0     0         0             0                      0           0   
2         0     0         0             0                      0           0   
3         0     0         1             0                      0           0   
4         0     0         0             0                      0           0   

   Disease  target      Disease_r  
0       20       1    PEPTICULCER  
1        0       1       DYSPNOEA  
2       21       1         ANEMIA  
3       22       1      PHEUMONIA  
4       23       1  PNECIMOTHORAX  

[5 rows x 28 columns]

In [24]:
df.shape

(350, 28)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 351
Data columns (total 28 columns):
 #   Column                                       Non-Null Count  Dtype 
---  ------                                       --------------  ----- 
 0   Age                                          350 non-null    int64 
 1   Sex                                          350 non-null    int64 
 2   Chest Pain                                   350 non-null    int64 
 3   Shortest of breath                           350 non-null    int64 
 4   Heaviness or tightness                       350 non-null    int64 
 5   Radiation into arms nack and jaw             350 non-null    int64 
 6   Congestion or burning                        350 non-null    int64 
 7   Abnormal breathing                           350 non-null    int64 
 8   Losing flat cause                            350 non-null    int64 
 9   Decrease of sterngth                         350 non-null    int64 
 10  Trobale with balanc

In [26]:
df.describe()

Age         Sex  Chest Pain  Shortest of breath  \
count  350.000000  350.000000  350.000000          350.000000   
mean    50.137143    0.762857    0.345714            0.562857   
std     17.485272    0.425940    0.476281            0.496743   
min      9.000000    0.000000    0.000000            0.000000   
25%     33.000000    1.000000    0.000000            0.000000   
50%     50.000000    1.000000    0.000000            1.000000   
75%     65.000000    1.000000    1.000000            1.000000   
max     88.000000    1.000000    1.000000            1.000000   

       Heaviness or tightness  Radiation into arms nack and jaw  \
count              350.000000                        350.000000   
mean                 0.154286                          0.077143   
std                  0.361740                          0.267200   
min                  0.000000                          0.000000   
25%                  0.000000                          0.000000   
50%                  0.000000                          0.000000   
75%                  0.000000                          0.000000   
max                  1.000000                          1.000000   

       Congestion or burning  Abnormal breathing  Losing flat cause  \
count             350.000000          350.000000         350.000000   
mean                0.088571            0.225714           0.080000   
std                 0.284531            0.418650           0.271682   
min                 0.000000            0.000000           0.000000   
25%                 0.000000            0.000000           0.000000   
50%                 0.000000            0.000000           0.000000   
75%                 0.000000            0.000000           0.000000   
max                 1.000000            1.000000           1.000000   

       Decrease of sterngth  ...  Debilitation       Fever   Clubbing  \
count            350.000000  ...    350.000000  350.000000  350.00000   
mean               0.131429  ...      0.077143    0.060000    0.04000   
std                0.338352  ...      0.267200    0.237827    0.19624   
min                0.000000  ...      0.000000    0.000000    0.00000   
25%                0.000000  ...      0.000000    0.000000    0.00000   
50%                0.000000  ...      0.000000    0.000000    0.00000   
75%                0.000000  ...      0.000000    0.000000    0.00000   
max                1.000000  ...      1.000000    1.000000    1.00000   

             Rash    Smocking  Hypertension  Hyperchoies terolamia  \
count  350.000000  350.000000    350.000000             350.000000   
mean     0.042857    0.177143      0.240000               0.105714   
std      0.202825    0.382336      0.427695               0.307912   
min      0.000000    0.000000      0.000000               0.000000   
25%      0.000000    0.000000      0.000000               0.000000   
50%      0.000000    0.000000      0.000000               0.000000   
75%      0.000000    0.000000      0.000000               0.000000   
max      1.000000    1.000000      1.000000               1.000000   

       Myocandial     Disease      target  
count  350.000000  350.000000  350.000000  
mean     0.031429   15.351429    0.748571  
std      0.174723   10.122144    0.434455  
min      0.000000    0.000000    0.000000  
25%      0.000000    7.000000    0.250000  
50%      0.000000   13.000000    1.000000  
75%      0.000000   28.000000    1.000000  
max      1.000000   29.000000    1.000000  

[8 rows x 27 columns]

#### divide the data into feature and target

In [46]:
X =df.iloc[:,:-1].values
y =df.iloc[:,-1].values

In [28]:
print(X.shape,y.shape)

(350, 27) (350,)


In [29]:
X

array([[31,  1,  1, ...,  0, 20,  1],
       [24,  0,  1, ...,  0,  0,  1],
       [50,  0,  1, ...,  0, 21,  1],
       ...,
       [31,  1,  0, ...,  0, 20,  1],
       [33,  1,  1, ...,  0, 23,  1],
       [66,  1,  1, ...,  0,  5,  1]])

In [30]:
X_encoded = pd.get_dummies(df) # this requers datafrrame as input

In [31]:
X_encoded.head().astype(int)

Age  Sex  Chest Pain  Shortest of breath  Heaviness or tightness  \
0   31    1           1                   1                       0   
1   24    0           1                   1                       0   
2   50    0           1                   1                       0   
3   36    0           1                   1                       0   
4   40    1           0                   1                       0   

   Radiation into arms nack and jaw  Congestion or burning  \
0                                 0                      1   
1                                 0                      1   
2                                 0                      0   
3                                 0                      0   
4                                 0                      0   

   Abnormal breathing  Losing flat cause  Decrease of sterngth  ...  \
0                   0                  0                     0  ...   
1                   1                  0                     0  ...   
2                   0                  0                     1  ...   
3                   1                  0                     0  ...   
4                   1                  0                     0  ...   

   Disease_r_ORTHOPNOEA  Disease_r_PALPITATION  Disease_r_PEPTICULCER  \
0                     0                      0                      1   
1                     0                      0                      0   
2                     0                      0                      0   
3                     0                      0                      0   
4                     0                      0                      0   

   Disease_r_PHARYNGITIS OR TONSILLITIS  Disease_r_PHEUMONIA  \
0                                     0                    0   
1                                     0                    0   
2                                     0                    0   
3                                     0                    1   
4                                     0                    0   

   Disease_r_PNECIMOTHORAX  Disease_r_PREVIOUS STROKE  \
0                        0                          0   
1                        0                          0   
2                        0                          0   
3                        0                          0   
4                        1                          0   

   Disease_r_RHEMATIC HEART  Disease_r_SINOATRIAL  Disease_r_minor symptoms  
0                         0                     0                         0  
1                         0                     0                         0  
2                         0                     0                         0  
3                         0                     0                         0  
4                         0                     0                         0  

[5 rows x 56 columns]

#### using onehot encoder

In [32]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [33]:
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[3])],remainder='passthrough')

In [34]:
X_new = ct.fit_transform(X)

In [35]:
X_new

array([[ 0.,  1., 31., ...,  0., 20.,  1.],
       [ 0.,  1., 24., ...,  0.,  0.,  1.],
       [ 0.,  1., 50., ...,  0., 21.,  1.],
       ...,
       [ 1.,  0., 31., ...,  0., 20.,  1.],
       [ 1.,  0., 33., ...,  0., 23.,  1.],
       [ 1.,  0., 66., ...,  0.,  5.,  1.]])

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_encoded,y,test_size = 0.2,random_state=0)

In [37]:
X_train.shape

(280, 56)

In [47]:
y_train.shape

(280,)

In [48]:
from sklearn.linear_model import LinearRegression # it is applicable to simple as well as multiple
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [49]:
y_pred = regressor.predict(X_train)
y_pred

array([2.80000000e+01, 1.60000000e+01, 8.00000000e+00, 6.00000000e+00,
       4.00000000e+00, 2.00000000e+01, 2.40000000e+01, 2.00000000e+01,
       8.00000000e+00, 2.30000000e+01, 1.80000000e+01, 1.00000000e+00,
       1.60000000e+01, 1.60000000e+01, 2.30000000e+01, 6.00000000e+00,
       3.00000000e+00, 1.80000000e+01, 2.80000000e+01, 2.70000000e+01,
       2.60000000e+01, 2.60000000e+01, 1.77635684e-14, 2.00000000e+01,
       2.80000000e+01, 1.70000000e+01, 6.00000000e+00, 9.00000000e+00,
       1.80000000e+01, 4.08562073e-14, 3.00000000e+00, 3.00000000e+00,
       8.00000000e+00, 1.80000000e+01, 6.00000000e+00, 2.00000000e+01,
       6.00000000e+00, 3.00000000e+00, 2.80000000e+01, 1.20000000e+01,
       8.00000000e+00, 1.10000000e+01, 2.20000000e+01, 1.70000000e+01,
       4.00000000e+00, 2.80000000e+01, 2.60000000e+01, 1.00000000e+00,
       2.00000000e+00, 2.00000000e+01, 1.90000000e+01, 1.40000000e+01,
       2.80000000e+01, 2.60000000e+01, 3.00000000e+00, 2.80000000e+01,
      

In [50]:
y_train

array([28, 16,  8,  6,  4, 20, 24, 20,  8, 23, 18,  1, 16, 16, 23,  6,  3,
       18, 28, 27, 26, 26,  0, 20, 28, 17,  6,  9, 18,  0,  3,  3,  8, 18,
        6, 20,  6,  3, 28, 12,  8, 11, 22, 17,  4, 28, 26,  1,  2, 20, 19,
       14, 28, 26,  3, 28,  6, 18, 28, 13,  0, 18, 19, 18,  3, 17, 28, 16,
       28, 13, 12,  3,  3, 11, 10, 13, 14,  1, 20, 10, 13,  3,  9, 18, 22,
       28,  3, 20,  4,  1,  5,  4, 20, 28,  0, 24, 13, 10, 16, 28, 28, 28,
        3, 28,  6, 28, 21,  8, 24, 28, 21,  1, 10,  9,  4, 26, 18, 18, 16,
       26, 28,  1, 20, 20,  3, 28, 24, 18,  2, 28, 28,  1,  9, 18,  2, 28,
       18,  0,  7, 13, 27,  8, 28, 23, 21, 26,  2, 28, 28,  3, 13,  1, 20,
       28, 15, 24, 13,  0,  8, 28, 22,  2,  9, 20, 16, 28, 17, 28, 19, 28,
        7,  7, 18,  8, 13, 18, 18, 26,  4, 18,  9, 27, 28, 28, 28,  6,  6,
        3, 16,  5, 21,  6, 20, 18,  8, 20, 18,  3, 18,  3, 16, 28, 21,  0,
       18,  9,  1,  1,  8,  8, 24, 24,  8, 28,  0, 19,  3, 28, 28, 28,  1,
       28, 28,  6,  6,  7

In [51]:
from sklearn.metrics import mean_squared_error
y_pred = regressor.predict(X_train) 
mse = mean_squared_error(y_train,y_pred)

In [52]:
mse

7.652311402771916e-27

In [53]:
from sklearn.metrics import root_mean_squared_error
y_pred = regressor.predict(X_train) 
mse = root_mean_squared_error(y_train,y_pred)
mse

8.747749083491088e-14

In [54]:
from sklearn.metrics import mean_absolute_percentage_error
y_pred = regressor.predict(X_train) 
mse = root_mean_squared_error(y_train,y_pred)
mse

8.747749083491088e-14